namespace OrderSphere.BuildingBlocks.Security;

/// <summary>
/// Ambient correlation slot, following the same pattern as <see cref="AmbientTenantContext"/>.
/// Holds the id that ties together every log record belonging to one logical operation, across
/// HTTP hops and Service Bus message boundaries alike.
/// <para>
/// API requests get it from the <c>X-Request-Id</c> header (generated by the API Gateway when
/// absent); worker message loops get it from the integration event being processed. Because the
/// slot is <see cref="AsyncLocal{T}"/>, the log enricher in ServiceDefaults reads it without
/// needing an <c>HttpContext</c> — the same enricher therefore works in APIs and workers.
/// </para>
/// <para>
/// This is log correlation, distinct from <c>IntegrationEvent.CorrelationId</c>, which is a
/// business identifier used for idempotency.
/// </para>
/// </summary>
public static class AmbientCorrelationContext
{
    private static readonly AsyncLocal<string?> Current = new();

    /// <summary>The correlation id set by the innermost open <see cref="BeginScope"/>, if any.</summary>
    public static string? Ambient => Current.Value;

    public static IDisposable BeginScope(string correlationId)
    {
        var previous = Current.Value;
        Current.Value = correlationId;
        return new Scope(previous);
    }

    private sealed class Scope(string? previous) : IDisposable
    {
        public void Dispose() => Current.Value = previous;
    }
}
